[tool.poetry]
name = "generative-art"
version = "0.1.0"
description = ""
authors = ["Pavel <useless.dinosaur@veloc1.me>"]

[tool.poetry.dependencies]
python = "^3.8"
pyglet = "^1.5.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
